nasa/cmr-graphql

serverless.yml, src/cmr/concepts/concept.js, src/cmr/concepts/subscription.js, src/datasources/__tests__/subscription.test.js, src/resolvers/__tests__/subscription.test.js, src/types/subscription.graphql, src/utils/__tests__/cmrDelete.test.js, src/utils/__tests__/cmrIngest.test.js, src/utils/cmrDelete.js, src/utils/cmrIngest.js, src/utils/mergeParams.js, src/utils/umm/subscriptionKeyMap.json
Adds `type` field to subscriptions, removed requirement of collectionConceptId field
Changed the subscription ingest path to the new path from CMR-8269
Added values for MetadataSpecification for ingesting subscriptions
=> EDSC-3420: Adds support for collection subscriptions

src/resolvers/__tests__/subscription.test.js, src/resolvers/subscription.js, src/types/subscription.graphql, src/utils/umm/subscriptionKeyMap.json
Adds creationDate and revisionDate fields to Subscription type.
Also fixes a bug where a collection was being returned if the subscription had no collectionConceptId, like when the subscription type is 'collection'
Subscription queries
query:
```
query Subscriptions($params: SubscriptionsInput) {
subscriptions(params: $params) {
count
items {
conceptId
type
creationDate
revisionDate 
collectionConceptId
collection {
conceptId
title
}
}
}
}
```
variables: 
```
{
"params": {
"type": "collection"
}
}
```
=> EDSC-3423: Adds creationDate and revisionDate fields to Subscription type

bin/deploy-bamboo.sh, src/utils/__tests__/getUserPermittedGroups.test.js
Adds two environment variables to the deploy script to be picked up from Bamboo. (Also sorted the list of variables so the diff is a bit misleading)
=> CMR-8424: Adds two new ENV variables and spacing in a test file

README.md, src/cmr/concepts/concept.js, src/datasources/__tests__/collection.test.js, src/datasources/__tests__/granule.test.js, src/datasources/__tests__/service.test.js, src/datasources/__tests__/subscription.test.js, src/datasources/__tests__/tool.test.js, src/datasources/__tests__/variable.test.js, src/utils/cmrQuery.js
Updates GraphQL to utilize Search After paging with CMR instead of Scroll Sessions which are being deprecated.
End users will have no impact, the back-end HTTP requests now utilize a different header.
1. Initiate a request providing parameters that bring results to a reasonable amount, including a page size that will minimize the number of pages. This request should also ask for the `cursor` to be returned
2. Run the request as many times as necessary, each time, updating the cursor parameter being sent with the one that comes back in the request.
3. When no results come back you should also notice the cursor comes back as `null`.
=> EDSC-3478: Updates paging to use search after instead of scroll sessions

src/datasources/__tests__/collection.test.js, src/resolvers/__tests__/collection.test.js, src/utils/__tests__/prepKeysForCmr.test.js, src/utils/prepKeysForCmr.js
When performing a collection search export in EDSC, selecting an organization facet with spaces results in 0 exported collections. EDSC is passing url encoded values to cmr-graphql, and cmr-graphql was encoding them a second time. 
Remove the encoding of CMR parameters. Passing non-encoded values is acceptable by CMR, and if cmr-graphql is given encoded values, passing them through as received will be accepted by CMR
Querying with encoded values
Query:
`query Collections($params: CollectionsInput) {
collections(params: $params) {
count
items {
conceptId
}
}
}`
Variables (in prod, will not return results):
`{
"params": {
"dataCenterH": "Advanced+Spaceborne+Thermal+Emission+and+Reflection+Radiometer+%28ASTER%29"
}
}`
Variables (locally, will return results):
`{
"params": {
"dataCenterH": …
=> EDSC-3556: Removes encoding of parameters

package-lock.json
npm audit fix
ran npm audit fix, which updated loader-utils
babel transpiling
run `npm audit`
before:
after:
=> EDSC-3575: fixed npm audit issue, updated loader-utils to 2.0.3

src/cmr/concepts/collection.js, src/cmr/concepts/concept.js, src/datasources/__tests__/collection.test.js, src/datasources/service.js, src/resolvers/__tests__/collection.test.js, src/resolvers/__tests__/service.test.js, src/resolvers/__tests__/tool.test.js, src/resolvers/__tests__/variable.test.js, src/resolvers/collection.js, src/types/collection.graphql, src/types/grid.graphql, src/types/service.graphql, src/types/tool.graphql, src/types/variable.graphql, src/utils/umm/collectionKeyMap.json, src/utils/umm/serviceKeyMap.json, src/utils/umm/toolKeyMap.json, src/utils/umm/variableKeyMap.json
Adding association_details field for variables, services, tools, and collections
Replaced data retrieved from the associations field to use the association_details field instead, and added association_details as a field for variables, services, tools, and collections types
Querying for services, variables, tools, and collections are expanded to include the new field. Previous queries that utilized the associations field to retrieve associated concepts i.e. { collections { items { variables {} }} are now using association_details instead. Tests were altered as well of course
Test that we can get back: tools, services, variables from the collection and the collections query for associated concepts
Test that we can get back: collections from tool, tools, service, services, variable, and …
=> EDSC 3648: As a cmr-graphql, I want to retrieve associationDetails for all supported types

README.md, src/cmr/concepts/collection.js, src/cmr/concepts/collectionDraft.js, src/cmr/concepts/collectionDraftProposal.js, src/cmr/concepts/concept.js, src/cmr/concepts/granule.js, src/cmr/concepts/service.js, src/resolvers/__tests__/dataQualitySummary.test.js, src/resolvers/__tests__/grid.test.js, src/types/grid.graphql, src/utils/umm/gridKeyMap.json
Since all concepts now support associations we should refactor some of the concept specific logic out to the concept parent (base class), while preserving the search functionality of extended classes that do not support associations such as granules, collection drafts, and collection draft proposals.
- Added association search to grids (was the only concept missing them)
- Refactored the association code (handled by a method "setEssentialJsonValues") out from extended classes into the base class "Concept". Those classes that do not support associations, explicitly delete the "setEssentialJsonValues" method in their constructors. The service class also adds more to that method.
All
- **Environment for testing:** SIT
- **Collection to test with:** C1200442362-CMR_ONLY
1. Search for the …
=> EDSC-3658: add associations to grid and refactor associations into base class

src/cmr/concepts/collection.js, src/cmr/concepts/concept.js, src/resolvers/__tests__/collection.test.js, src/types/collection.graphql
Add support for querying cmr-graphql with a list of shortName values.
Send multiple requests to CMR (one for each provided shortName). Since collection inherits from concept, I adapted the fetch and parse methods to handle when an array of shortName values is a query field.
I wonder if there should be a limit on how many shortName values you can request though (I was thinking there might be potential for launching some kind of attack if each shortName is an additional CMR request and many shortName values were included in the query? Maybe this is already handled somewhere though?)
Collections concept, possibly other concepts as well. Anywhere collection fetching or parsing is used (I had to change some existing code to make things work).
1. Go to [cmr-graphql …
=> EDSC-3674: Query collections by multiple shortNames.

src/cmr/concepts/draftConcept.js, src/datasources/__tests__/collectionDraft.test.js, src/datasources/__tests__/toolDraft.test.js, src/datasources/__tests__/variableDraft.test.js, src/resolvers/__tests__/collectionDraft.test.js, src/resolvers/__tests__/toolDraft.test.js, src/resolvers/__tests__/variableDraft.test.js, src/utils/__tests__/mmtQuery.test.js, src/utils/mmtQuery.js
Updated the draft retrieval endpoint as MMT updated the endpoint.
- Updated draftConcept.js with the new endpoint: /api/drafts/:id?draft_type=:draftType -> /api/draftType/id
- Parsing the conceptType in draftConcept.js, MMT requires the to be tool_drafts, variable_drafts or collection_drafts
=> CMR-9191: Update the draft retrieval endpoint in CMR-GraphQL

src/graphql/handler.js, src/utils/mmtQuery.js
After deploying MMT-3263 to SIT, noticed I was getting an unauthorized error in GraphQL. 
After debugging, noticed that the new MMT Draft API requires username as a required param.
Summarize what you changed.
In mmtQuery.js I needed to add User which was already being declared in handler.js as edlUsername. So in handler.js I assigned edlUsername to the requestHeader as User.
=> CMR-9254: Unable to retrieve drafts in SIT for MMT Preview

package-lock.json
supersedes https://github.com/nasa/cmr-graphql/pull/57
updates sub-dependencies to address ReDos reported for fast-xml-parser
ran the following:
```
git clone git@github.com:NASA/cmr-graphql
cd cmr-graphql/
git checkout -b EDSC-3805-2
npm audit fix
```
cmr-graphql
1.  npm audit
=> EDSC-3805: ran npm audit fix

src/resolvers/__tests__/service.test.js, src/resolvers/service.js, src/types/service.graphql
Adding variable associations to services.
Service to Variable associations
=> EDSC-3817: Adding variables to services

src/utils/__tests__/parseRequestedFields.test.js, src/utils/parseRequestedFields.js
When requesting collections as a subquery of other concepts, specifically services and variables, we need to include the parent concept's `conceptId` as a requested field, even if the user did not request that field. This ensures the sub query has the required fields to query collections.
Added `conceptId` as a requestedField when it doesn't exist for services and variables that are requesting collections
Services and Variables queries with a collections sub query
Using this query will result in all the collections being returned, because the query does not request the service's conceptId. This PR forces the conceptId to be included, so the correct collections are returned.
```
query Services($serviceParams: ServicesInput) {
services(params: $serviceParams) {
items {
name
collections { …
```
=> EDSC-3895: Include conceptId in subqueries if necessary

serverless.yml
…on field"
We need to add the "Aggregation" for the service concept into `cmr-graphql` This field is contained on the service v1.5.2 (https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/service/v1.5.2)
"Aggregation is JSON field" which is a child of the `serviceOptions` field.
Update the UMM-S version being queried from CMR to v1.5.2
UMM-S/service queries
Query for a services which contains the aggregation field such as `S1200463978-CMR_ONLY` in the SIT env
N/A
- [n/a] I have added automated tests that prove my fix is effective or that my feature works
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
=> CMR-9489: Bumping the UMM-S record to add "Aggregation" field

src/cmr/concepts/concept.js, src/cmr/concepts/draft.js, src/cmr/concepts/subscription.js, src/cmr/concepts/variable.js, src/datasources/__tests__/draft.test.js, src/datasources/__tests__/variable.test.js, src/datasources/variable.js, src/graphql/handler.js, src/resolvers/__tests__/__mocks__/mockServer.js, src/resolvers/__tests__/draft.test.js, src/resolvers/__tests__/variable.test.js, src/resolvers/collection.js, src/resolvers/draft.js, src/resolvers/service.js, src/resolvers/variable.js, src/types/draft.graphql, src/types/variable.graphql, src/utils/__tests__/cmrIngest.test.js, src/utils/cmrIngest.js
Added support for Publish Variable Draft and Published Delete Draft. 
List impacted areas.
1.) Has a Published Collection Record handy.
2.) Publish a variable draft
```
mutation PublishDraft(
$draftConceptId: String!
$nativeId: String!
$ummVersion: String!
) {
publishDraft(
draftConceptId: $draftConceptId
nativeId: $nativeId
ummVersion: $ummVersion
) {
conceptId
revisionId
warnings
existingErrors
}
}
```
Variables: 
```
{
"draftConceptId": "VD1000000001-EXAMPLE",
"nativeId": "service-1",
"ummVersion": "1.2.0"
"collectionConceptId: "C100000-EXAMPLE"
}
```
Testing Delete
```
mutation DeleteService(
$providerId: String!
$nativeId: String!
) {
deleteTool(
providerId: $providerId
nativeId: $nativeId
) {
conceptId
revisionId
}
}
```
Variables:
```
{
"providerId": "EXAMPLE",
"nativeId": …
```
=> MMT-3417: As a MMT dev, I want to be able to CRUD UMM-V records in CMR GraphQL

src/cmr/concepts/concept.js, src/resolvers/__tests__/variable.test.js
Fixed the bug that was causing the Related URL tab to have no values in MMT.
=> GQL-10: Related URL tab is showing No value for provided message

serverless.yml
When working on creating a publish mutation in MMT React, I noticed when trying to publish a draft with Related URL, the validation from CMR was failing. CMR was returning with errors "MimeType and Format are extraneous keys"
After debugging noticed there was a version miss match where MMT is using 1.2.0 for the schema but when publish GraphQL is sending version 1.1 to CMR. 
So CMR is trying to validate a 1.2.0 draft with version 1.1.
Updating the version for UMM-T in the serverless.yml to the latest.
=> MMT-3411: As a metadata user, I want to publish a UMM record

requirements.txt
Updating version of earthdata-varinfo to 2.2.0
Updating version of earthdata-varinfo to 2.2.0
Updating version of earthdata-varinfo to 2.2.0
Python Lambda
Use GraphQL to generate Variables
=> DAS-2049 Updating earthdata-varinfo to 2.2.0

src/types/collection.graphql, src/types/service.graphql, src/types/tool.graphql, src/types/variable.graphql, src/utils/umm/collectionKeyMap.json, src/utils/umm/serviceKeyMap.json, src/utils/umm/toolKeyMap.json, src/utils/umm/variableKeyMap.json
When working on the Edit Publish Button in MMT, we noticed we needed the raw UMM metadata from GraphQL like how drafts supports it right now.  
Please summarize the feature or fix.
For Collection, Service, Variable and Tool added a `ummMetadata` field that will show the raw UMM value that is being returned from CMR.
=> GQL-25: As MMT, I want query the raw UMM metadata for published record

src/types/service.graphql, src/types/tool.graphql, src/types/variable.graphql
Adds keyword parameter to service, tool, and variable searching
Added the params to the schema
Services, Tools, and Variables schemas
- **Environment for testing:** ANY
- **Collection to test with:** N/A
1. Search for a service with a keyword parameter and confirm results are returned
2. Search for a tool with a keyword parameter and confirm results are returned
3. Search for a variable with a keyword parameter and confirm results are returned
=> GQL-28: Adds keyword parameter to service, tool, and variable searching

src/cmr/concepts/collection.js, src/datasources/__tests__/collection.test.js, src/datasources/collection.js, src/graphql/handler.js, src/resolvers/__tests__/__mocks__/mockServer.js, src/resolvers/__tests__/collection.test.js, src/resolvers/collection.js, src/resolvers/service.js, src/resolvers/subscription.js, src/resolvers/tool.js, src/resolvers/variable.js, src/types/collection.graphql
Added `deleteCollection` mutation
Given a publish Collections native-id and provider-id, graphql now can call CMR DELETE endpoint and delete the given collection.
```
mutation Mutation($providerId: String!, $nativeId: String!) {
deleteCollection(providerId: $providerId, nativeId: $nativeId) {
conceptId
revisionId
}
}
```
Variables: 
```
{
"providerId": "SEDAC",
"nativeId": "collection0"
}
```
=> MMT-3420: As a MMT dev, I want to be able to Delete UMM-C published in CMR GraphQL

src/cmr/concepts/__tests__/collection.test.js, src/cmr/concepts/__tests__/service.test.js, src/cmr/concepts/__tests__/tool.test.js, src/cmr/concepts/__tests__/variable.test.js, src/cmr/concepts/service.js, src/cmr/concepts/tool.js, src/cmr/concepts/variable.js, src/types/service.graphql, src/types/tool.graphql, src/types/variable.graphql
Adding provider param and fixing request issue in services, variables, and tools
Adds the provider param and adds the provider and keyword to the permitted keys
Services, Tools, and Variables queries
- **Environment for testing:** ANY
- **Collection to test with:** n/a
1. Confirm the provider and keyword parameters filter the search results for Tools in cmr-graphql
2. Confirm the provider and keyword parameters filter the search results for Services in cmr-graphql
3. Confirm the provider and keyword parameters filter the search results for Variables in cmr-graphql
=> MMT-3552: Adding provider param and fixing request issue

src/cmr/concepts/__tests__/provider.test.js, src/cmr/concepts/provider.js, src/datasources/__tests__/provider.test.js, src/datasources/provider.js, src/graphql/handler.js, src/resolvers/__tests__/__mocks__/mockServer.js, src/resolvers/__tests__/provider.test.js, src/resolvers/index.js, src/resolvers/provider.js, src/types/index.js, src/types/provider.graphql, src/utils/providersQuery.js, src/utils/umm/providerKeyMap.json
Adds a query to get all providers using the `/ingest/providers` endpoint for use in MMT
Adds a provider type, concept, and resolver to query the endpoint
Providers query
- **Environment for testing:** ANY
- **Collection to test with:** N/A
1. Query for providers
2. Confirm the count and items are returned as expected
=> MMT-3493: Adding providers query

serverless.yml
The granule info panel wasn't showing certain fields
Updated umm-g version
Granule searches
Navigate to granule information and verify SizeInBytes is there, and ENVI format is present when its in the metadata.
=> EDSC-3988 updates umm-g version

.github/workflows/ci.yml
Github Actions has warnings that we need to get off node16. This PR updates the actions versions to actions that use node20.
=> GQL-37: Updates actions to use node20 actions

src/cmr/concepts/concept.js, src/cmr/concepts/orderOption.js, src/cmr/concepts/provider.js, src/resolvers/__tests__/orderOption.test.js, src/resolvers/orderOption.js, src/resolvers/service.js, src/types/orderOption.graphql
Adds support for collections query within order options
Added a resolver for collections that allows them to be queried from within an order option.
Order option queries.
=> MMT-3433: Adds support for collections query within order options

src/cmr/concepts/concept.js, src/cmr/concepts/draftConcept.js, src/constants/index.js, src/resolvers/__tests__/collection.test.js, src/resolvers/__tests__/service.test.js, src/resolvers/__tests__/tool.test.js, src/resolvers/__tests__/variable.test.js, src/resolvers/collection.js, src/resolvers/service.js, src/resolvers/tool.js, src/resolvers/variable.js, src/types/collection.graphql, src/types/service.graphql, src/types/tool.graphql, src/types/variable.graphql, src/utils/parseRequestedFields.js
Adds a `revisions` return field for Collection, Service, Tool and Variable types.
Collection, Service, Tool and Variable types have a new field, `revisions` which will return all of the revisions of each concept
Query for Collections, Services, Tools and Variables, include the `revisions` field and ensure all revisions (there is a CMR max of 10) are returned
=> MMT-3695: Implements revisions resolver

src/resolvers/__tests__/collection.test.js, src/resolvers/__tests__/orderOption.test.js, src/resolvers/__tests__/service.test.js, src/resolvers/collection.js, src/resolvers/orderOption.js, src/resolvers/service.js
Replaces default responses for search results with empty arrays, instead of `null`.
=> MMT-3645: Return [] over null when no results are found

src/cmr/concepts/acl.js, src/cmr/concepts/collection.js, src/cmr/concepts/collectionDraftProposal.js, src/cmr/concepts/concept.js, src/cmr/concepts/draft.js, src/cmr/concepts/draftConcept.js, src/cmr/concepts/granule.js, src/cmr/concepts/provider.js, src/cmr/concepts/subscription.js, src/cmr/concepts/tagDefinition.js, src/datasources/graphDb.js, src/datasources/graphDbDuplicateCollections.js, src/types/acl.graphql, src/utils/mmtQuery.js, src/utils/pickIgnoringCase.js
Added permitted_group to configuration array that prevents the index of array values from being added on its way to CMR.
=> MMT-3526: Updates the permitted_group parameter sent to CMR

src/graphql/handler.js, src/permissions/__tests__/permissions.test.js, src/permissions/index.js, src/permissions/rules/__tests__/isLocalMMT.test.js, src/permissions/rules/isLocalMMT.js, src/utils/__tests__/fetchLaunchpadEdlUid.test.js, src/utils/__tests__/isOfflineMMT.test.js, src/utils/fetchLaunchpadEdlUid.js, src/utils/isOfflineMMT.js
Launchpad tokens don't use the `Bearer ` prefix, my previous PR assumed they did. This PR removes that logic
=> GQL-42: Fixes bug with launchpad tokens

src/datasources/__tests__/group.test.js, src/datasources/group.js, src/types/group.graphql
Implements paging for groups query by adding `limit` and `offset`. Defaults `limit` to `20` and `offset` to `0`
`groups` query
Perform `groups` query that will return many results, like `name: ""`. Ensure you see full groups count but only 20 results. 
Perform same query and provide `limit` and `offset` parameters
=> GQL-42: Implements paging for groups query

src/types/orderOption.graphql
Add provider id to order options
Added providerId to the query
orderOption queries
- **Environment for testing:** N/A
- **Collection to test with:** N/A
1. Query for a providerId on an order option and confirm it returns as expected
=> GQL-48: Add provider id to order options

src/resolvers/__tests__/draft.test.js, src/resolvers/draft.js, src/types/draft.graphql
CMR removed the requirement for a variable draft to have a collection concept-id associated when publish a variable record. This PR is removing the check for collectionConceptId for variable draft
1. Create a Variable draft
2. Publish the variable draft without specifying a collection concept id
=> MMT-3702: Adjust MMT Variable to Collection associations to use updated GraphQL operation

src/resolvers/__tests__/acl.test.js, src/resolvers/__tests__/group.test.js, src/resolvers/acl.js, src/resolvers/group.js, src/types/acl.graphql, src/types/group.graphql
Adds the ability to query for Acls that belong to a group, from within a group query.
=> GQL-52: Allow querying for Acls from within a group

serverless-configs/env.yml
Update umm-c version from 1.18.0 to 1.18.1
New changes to umm 1.18.1 are: 
- UMM-C schema added "minimum": 0 for Size in GetDataType.
- UMM-C schema added "minimum": 0 for AverageFileSize, TotalCollectionFileSize in FileArchiveInformationType and FileDistributionInformationType.
There were no new fields added and these changes do not need any GraphQL schema change. Updates the ummCollectionVersion in env.yml
=> GQL-60: As a CMR GraphQL operator, I want to query new UMM-C v1.18.1 in the search response

src/permissions/__tests__/permissions.test.js, src/permissions/acls/__tests__/canCreateProviderGroups.test.js, src/permissions/acls/__tests__/canCreateSystemGroups.test.js, src/permissions/acls/__tests__/canReadSystemGroups.test.js, src/permissions/acls/canCreateProviderGroups.js, src/permissions/acls/canCreateSystemGroups.js, src/permissions/acls/canReadSystemGroups.js, src/permissions/index.js
In MMT, a user reported that even they don't have system level permission they should still be able to view their provider level permission.
Updates the rules and checking in shield. 
**Query**
- If params.tag includes CMR, check if the user has system level permission
- Else let them read permission 
**Mutation**
- If params.tag includes CMR, check if the user has system level permission
- If params.tag does not include CMR and includes some other provider, check if the user has create group permission for that provider
- If the user does not have a tag, allow them to update. 
List impacted areas. SIT/UAT/PROD
=> GQL-61: As a user, I can read and update provider level group permissions

package-lock.json
Snyk vul issue
Update dependencies with `npm audit fix`
Axios request updates minor version bumps on other libraries. Fairly large `npm audit bump` on this package-lock
- **Environment for testing:*SIT*
- **Collection to test with:*Any*
1. Ensure that the reported `snyk` vul is no longer being reported in the build
2. Regression test GQL functionality to ensure that functionality has not changed
- [N/A] I have added automated tests that prove my fix is effective or that my feature works
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
=> GQL-66: Run npm audit fix

src/cmr/concepts/concept.js, src/resolvers/__tests__/granule.test.js
The headers value gets modified with a search-after header when using a cursor. The search-after header is persisting when calling granule query with a subquery of collection.
Make a copy of the headers value so the original headers value isn't modified.
graphQL calls for a Granule query with a Collection subquery when passing in a cursor.
Run the following query in PROD(need to make sure you pass in a cursor and it returns more than 20 items):
query getGranules($params: GranulesInput) {
granules(params: $params) {
count
cursor
items {
title
conceptId
collection
{           conceptId           shortName           version           title         }
cloudCover
lines
boxes
polygons
points
links
timeStart
timeEnd
relatedUrls
}
}
}
Variables:
{
"params":
{   "provider": "LPCLOUD",   "entryId": …
=> GQL-70: GraphQL granules call returns error during expanded temporal range. 

src/cmr/concepts/concept.js, src/cmr/concepts/draft.js, src/cmr/concepts/subscription.js, src/datasources/__tests__/draft.test.js, src/datasources/__tests__/subscription.test.js, src/utils/cmrDelete.js
LPDAAC ran into an issue in MMT in production and couldn't publish their draft record.
https://mmt.earthdata.nasa.gov/drafts/collections/CD3244307783-LPCLOUD
After some initial investigation it was determined that the native id was not fully URL encoded: The Original Native ID is:
"native-id" : "VIIRS/NPP BRDF/Albedo Model Parameters Daily L3 Global 1km SIN Grid V002"
The CMR request has it as: 
VIIRS/NPP%20BRDF/Albedo%20Model%20Parameters%20Daily%20L3%20Global%201km%20SIN%20Grid%20V002
The non encoded slashes / are adding to the invalid URL:
/ingest/publish/CD3244307783-LPCLOUD/VIIRS/NPP%20BRDF/Albedo%20Model%20Parameters%20Daily%20L3%20Global%201km%20SIN%20Grid%20V002
So the CMR can't find the correct API endpoint.
I looked through all the files where `{nativeId}` was being used in a …
=> GQL-75: Encodes native id before sending it to CMR.

src/cmr/concepts/subscription.js, src/datasources/__tests__/subscription.test.js, src/graphql/handler.js, src/types/subscription.graphql
CMR GraphQL was unable to create or edit subscriptions. CMR was returning an invalid content type error.
Include the correct `Content-Type` header on subscription ingest requests.
I also fixed the issue where our error message did not include the `requestId`
Subscription mutations
Create mutation:
```
mutation CreateSubscription($params: CreateSubscriptionInput) {
createSubscription(
params: $params
) {
conceptId
revisionId
nativeId
}
}
```
Variables:
```
{
"params": {
"name": "Example Subscription",
"query": "polygon=-18,-78,-13,-74,-16,-73,-22,-77,-18,-78",
"subscriberId": "YOUR USERNAME",
"type": "collection"
}
}
```
Also remember to include an EDL token with the request.
Update mutation:
Be sure to copy the `nativeId` out of the response from the create mutation
```
mutation …
```
=> GQL-80: Adds content-type header to subscription ingest requests. Fixes undefined request id in error message

serverless-configs/env.yml
Updates the ummSubscriptionVersion to 1.1.1
Subscription mutations
Create mutation:
```
mutation CreateSubscription($params: CreateSubscriptionInput) {
createSubscription(
params: $params
) {
conceptId
revisionId
nativeId
}
}
```
Variables:
```
{
"params": {
"name": "Example Subscription",
"query": "polygon=-18,-78,-13,-74,-16,-73,-22,-77,-18,-78",
"subscriberId": "YOUR USERNAME",
"type": "collection"
}
}
```
Also remember to include an EDL token with the request.
Update mutation:
Be sure to copy the nativeId out of the response from the create mutation
```
mutation UpdateSubscription($params: UpdateSubscriptionInput) {
updateSubscription(params: $params) {
conceptId
revisionId
}
}
```
Variables:
```
{
"params": {
"nativeId": "NATIVEID FROM CREATE MUTATION",
"name": "Example Subscription …
```
=> GQL-80: Update ummSubscriptionVersion

src/resolvers/__tests__/collection.test.js, src/types/collection.graphql
Exposed EntryId to collections graphql requests
Added EntryId to collection.graphql
graphql-cmr
1. make a new graphql call with the following query
query GetProjectCollections(
$params: CollectionsInput
) {
collections(params: $params) {
items {
entryId
shortName
version
}
}
}
2. ensure entryId is returned in the response
=> GQL-79: exposed EntryId

serverless-configs/env.yml, src/cmr/concepts/__tests__/concept.test.js, src/cmr/concepts/concept.js, src/datasources/__tests__/granule.test.js, src/datasources/granule.js
In CMR STAC we are calling a `Granule` query which has collections fields. In order to complete this request, GraphQL calls `.umm_json` and `.json` endpoint in CMR. Depending on the usage of CMR, something we are seeing an error: `Inconsistent data prevented GraphQL from correctly parsing results (JSON Hits: 151344631, UMM Hits: 151344630)`.
If CMR Hits are different, we are now comparing the formats that were returned.
1. If the CMR Hits are the same, return the result.
2. If the CMR Hits are different but the list of items from both response are the same, return the result.
3. If the CMR Hits are different and the list of items from both response are not the same, figure out which endpoint the conceptId is missing and try to refetch. 
- If the missing concept is found, add the missing …
=> GQL-69: GraphQL granules call returns random results

package-lock.json, src/permissions/__tests__/fallbackError.test.js, src/permissions/index.js, src/utils/__tests__/parseError.test.js, src/utils/parseError.js
When a user tries to Save & Publish, occationaly an error will come back from CMR. Previously, every cmr error would return the same error message: 'An unknown error occurred. Please refer to the ID ${requestId} when contacting Earthdata Operations (support@earthdata.nasa.gov).' This ticket surfaces both the location of the error and the error message itself. It also preserves how error messages were handled previously. 
Two things: 
1. Allow external errors to surface for users who get back cmr errors, not just developers.
2. Correctly parse errors that contain a path so that mmt can make notifications with them
index.js under permissions
parseError.js
- **Environment for testing: local
- **Collection to test with: your own
1. Create a local collection draft that is ready to publish. …
=> GQL-87: Bug: Surface cmr errors for user readability

src/cmr/concepts/granule.js, src/datasources/__tests__/granule.test.js
The query EDSC uses to retrieve granule download links is not taking into account the `linkTypes` param that is being provided because it is nested within the `params` object.
Used the `mergeParams` util to ensure we see the `linkTypes` param regardless of where it is supplied.
Granule queries with the `linkTypes` param
Query
```
query GetGranuleLinks($params: GranulesInput) {
granules(params: $params) {
cursor
items {
links
}
}
} 
```
Variables
```
{
"params": {
"exclude": {},
"options": {},
"conceptId": [],
"twoDCoordinateSystem": {},
"limit": 50,
"linkTypes": [
"data",
"s3",
"browse"
],
"collectionConceptId": "C2276336440-LARC_ASDC"
}
} 
```
Ensure that only the correct link types are returned (data, s3 and browse)
=> GQL-89: Honor the linkTypes param when it is nested within GranulesInput params

src/resolvers/__tests__/granule.test.js, src/types/granule.graphql
The CloudCover field in the Granule type is currently an Int, but that value needs to be a Float
Updated the type in the schema. 
CMR granule endpoints return different types. `.json` returns Strings while `.umm_json` returns a Float. I updated the tests to correctly reflect this
Granule queries with CloudCover
This query shows a PROD collection that does have floating point CloudCover values
Query
```
query Collection($params: CollectionInput) {
collection(params: $params) {
granules {
count
items {
conceptId
cloudCover
}
}
}
}
```
Variables
```
{
"params": {
"conceptId": "C3020920290-OB_CLOUD"
}
}
```
=> GQL-88: Updates CloudCover type

src/cmr/concepts/granule.js, src/resolvers/__tests__/granule.test.js, src/types/granule.graphql, src/utils/umm/granuleKeyMap.json
Adds additionalAttributes field to Granule 
Adds attribute parameter to GranulesInput
Adds shortName parameter to GranulesInput
Granule queries
You can try adding/removing the different attribute variables to see different results being returned.
Query
```
query Granules($params: GranulesInput) {
granules(params: $params) {
count
items {
conceptId
additionalAttributes
}
}
}
```
Variables
```
{
"params": {
"provider": "ASF",
"shortName": "SEASAT_SAR_L1_TIFF",
"attribute": [
"string,GRANULE_TYPE,SEASAT_STD_FRAME",
"float,OFF_NADIR_ANGLE,-1",
"string,ASCENDING_DESCENDING,ASCENDING"
]
}
}
```
=> GQL-92: Adds additionalAttributes field to Granule and attribute parameter to GranulesInput

src/cmr/concepts/granule.js, src/resolvers/__tests__/granule.test.js, src/types/granule.graphql, src/utils/umm/granuleKeyMap.json
Adds revisionDate, createdAt and productionDate granule parameters. 
Adds revisionDate granule field
Granule queries
Add/remove the different variables to test each parameter
Query
```
query Granules($params: GranulesInput) {
granules(params: $params) {
count
items {
conceptId
timeEnd
timeStart
revisionDate
}
}
}
```
Variables
```
{
"params": {
"provider": "ASF",
"createdAt": "2020-01-01,2020-01-02",
// "productionDate": "2020-01-01,2020-01-02",
// "revisionDate": "2020-01-01,2020-01-02",
// "temporal": "2020-01-01,2020-01-02",
// "updatedSince": "2020-01-01"
}
}
```
=> GQL-43: Adds revisionDate, createdAt and productionDate granule parameters. Adds revisionDate granule field

serverless-configs/env.yml
Update UMM-C from 1.18.1 to 1.18.2
[CMR-10173](https://bugs.earthdata.nasa.gov/browse/CMR-10173), UMM-C schema added PREPRINT, INREVIEW, and SUPERSEDED enums to CollectionProgress
[CMR-10173](https://bugs.earthdata.nasa.gov/browse/CMR-10173), UMM-C schema removed NOT APPLICABLE enum in CollectionProgress
[CMR-10173](https://bugs.earthdata.nasa.gov/browse/CMR-10173), UMM-C schema added IsPreviousVersionOf and IsNewVersionOf enums to AssociatedDOIs/Type
There were no new fields added and these changes do not need any GraphQL schema change. Updates the ummCollectionVersion in env.yml to 1.18.2
env.yml
1. double check all tests pass and environment still works as expected
2. Step 2...
Please include relevant screenshots or files …
=> GQL-73: Update GraphQL to the new UMM-C version for the Web Unitification Round 2 changes.

src/cmr/concepts/collection.js, src/resolvers/__tests__/collection.test.js
Users are unable to view C1000000321-SEDAC in production. It comes back with a "TypeError: Cannot read properties of undefined (reading 'ArchiveAndDistributionInformation')"
This happens we getCollection calls revisions and tries to read the umm of each revision. In the case of deleted revisions, there is no umm. So I created a default for the umm of a revision. 
collection.js under concepts
- **Environment for testing: UAT
- **Collection to test with: 
https://mmt.uat.earthdata.nasa.gov/collections/C1265136920-OB_CLOUD
https://mmt.uat.earthdata.nasa.gov/collections/C1265136919-OB_CLOUD
https://mmt.uat.earthdata.nasa.gov/collections/C1265136924-OB_CLOUD
https://mmt.uat.earthdata.nasa.gov/collections/C1265136917-OB_CLOUD
1. Point cmr-graphql to UAT
2. Use reference picture below to set up …
=> GQL-85: Cannot view collection when a revision doesn't have UMM

cdk/graphql/lib/graphql-stack.ts
Update UMM-C schema from 1.18.2 to 1.18.3 as seen here: https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.18.3
Changes include:
UMM-C schema added URLMimeType enum "application/geo+json"
UMM-C schema updated 'DOI/PreviousVersion/Version' definition
UMM-C schema corrected spelling for Temporal resolution 'Constant'
UMM-C schema updated media type definition
This only required a single version bump in GQL without any other changes.  
- **Environment for testing: local
- **Collection to test with: local
1. Spin up local graphql and make sure you can ingest a draft with 1.18.3 changes
=> GQL-103: Updating UMM-C shema to 1.18.3

cdk/graphql/lib/graphql-stack.ts, src/cmr/concepts/__tests__/draft.test.js, src/cmr/concepts/collection.js, src/cmr/concepts/concept.js, src/cmr/concepts/draft.js, src/cmr/concepts/visualization.js, src/constants/index.js, src/datasources/__tests__/draft.test.js, src/datasources/__tests__/visualization.test.js, src/datasources/visualization.js, src/graphql/handler.js, src/resolvers/__tests__/__mocks__/mockServer.js, src/resolvers/__tests__/collection.test.js, src/resolvers/__tests__/draft.test.js, src/resolvers/__tests__/visualization.test.js, src/resolvers/collection.js, src/resolvers/draft.js, src/resolvers/index.js, src/resolvers/visualization.js, src/types/collection.graphql, src/types/draft.graphql, src/types/index.js, src/types/visualization.graphql, src/utils/parseRequestedFields.js, src/utils/umm/tagKeyMap.json, src/utils/umm/visualizationKeyMap.json
Adds UMM-Vis
New queries and mutations for UMM-Vis
```
query Visualizations($params: VisualizationsInput) {
visualizations(params: $params) {
count
items {
conceptId
revisionId
name
title
}
}
}
```
```
query Visualization($params: VisualizationInput) {
visualization(params: $params) {
conceptId
description
generation
identifier
metadataSpecification
name
nativeId
revisionDate
revisionId
revisions {
count
}
scienceKeywords
spatialExtent
specification
subtitle
temporalExtent
title
ummMetadata
visualizationType
collections {
count
}
}
}
```
```
query Drafts($params: DraftsInput) {
drafts(params: $params) {
count
items {
conceptId
name
previewMetadata {
... on Visualization {
name
}
}
}
}
}
```
```
mutation IngestDraftMutation(
$conceptType: DraftConceptType!
$metadata: JSON!
$nativeId: …
```
=> GQL-99: Adds UMM-Vis

src/resolvers/__tests__/visualization.test.js, src/types/visualization.graphql
Adding userId to Visualization so that I can call userId on past revisions
Added userId to visualization
visualization.graphql
- **Environment for testing:SIT
- **Collection to test with: VIS1200485038-MMT_1
1. Call userId on revisions under Visualization, should come up with whomever made the changes to a particular revision.
Please include relevant screenshots or files that would be helpful in reviewing and verifying this change
=> GQL-116: Adding UserId to Visualization

package-lock.json, src/resolvers/__tests__/citation.test.js, src/types/citation.graphql, src/utils/umm/citationKeyMap.json
Allow Citation to return ummMetadata
Add ummMetadata to graphQL
Citation
Make sure you can get ummMetadata from a Citation in graphQL
Login to Apollo Studio
Make sure you can get ummMetadata from Citation ie
query ExampleQuery {
citation {
conceptId
ummMetadata
}
}
=> GQL-123: Adding ummMetadata to Citation

src/datasources/__tests__/graphDbAssociatedCitations.test.js, src/resolvers/__tests__/collection.test.js, src/resolvers/collection.js, src/types/collection.graphql, src/utils/parseRequestedFields.js
You can query for associatedCitations on a Collection and receive back a valid response. As is the case with Collection: C1200484122-MMT_2. It is associated with [CIT1200485865-MMT_2](http://localhost:5000/citations/CIT1200485865-MMT_2) however you won't see that association in [cmr ](http://example.com/)anywhere as it only exists in graphdb. 
In graphql, we need to expose the citations that are found in the associationDetails/cmr like we do for variables, services, and tools.
Added citations to collection.graphql and created the resolver
Collection.graphql
collection/resolver
- **Environment for testing: SIT
- **Collection to test with: 
Collection to associate to: C1200411035-ARCTEST
Citation to associate to above Collection: CIT1200485769-MMT_1
1. In graphql, query for …
=> GQL-130: Exposing associated citations from CMR on Collection and disable associatedCitations from graphdb for now
